Content tests
BDSA-2021/BDSA21-Say-AAAAAA pull request #36
Opened 2021-12-05 11:23 UTC by YoHype

## Checklists
### Types of changes

- [ ] Fix (non-breaking change that fixes existing issue)
- [ ] Feature (non-breaking change that adds a feature)
- [ ] Breaking change (fix or feature that breaks or removes other functionality)

### Pre-flight checklist

- [ ] PR changes requires documentation change
  - [ ] I have updated the documentation accordingly
- [ ] I have tested my change, and run all unit tests 
- [ ] I ran ``dotnet format`` and committed+pushed the result

## Description

## Why

### Fixes issues:

- [x] #[some issue]

## How has this been tested

## Screenshots of the solution (if appropriate)

2021-12-07 22:13 UTC, JoachimBorup requested changes
Should `SELearning.Core/.DS_Store`, ` SELearning/appsettings.Development.json`, `SELearning/appsettings.json`, and `SELearning/wwwroot/css/site.css` be deleted? I don't know if they're part of something, or were accidentally created and committed.

2021-12-07 22:13 UTC, JoachimBorup commented on SELearning.Infrastructure.Tests/Content/ContentRepositoryTests.cs
> +    // }
What is this? Left-over junk code that hasn't been deleted, or something we should implement?

2021-12-07 22:13 UTC, JoachimBorup commented on SELearning.Infrastructure/ContentContext.cs
> +    protected override void OnModelCreating(ModelBuilder modelBuilder)
Is there a reason to override this method with an empty method?

2021-12-08 12:14 UTC, JoachimBorup approved these changes

2021-12-08 12:17 UTC, avborup approved these changes

2021-12-08 14:39 UTC, merged